//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knowledge.Demonstrator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousImagePath {
            get {
                return ((string)(this["PreviousImagePath"]));
            }
            set {
                this["PreviousImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3840522b396e4b9da09cf765b34ba35e")]
        public string SubscriptionKey1 {
            get {
                return ((string)(this["SubscriptionKey1"]));
            }
            set {
                this["SubscriptionKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("025681452da1432783fa829e915ff41e")]
        public string SubscriptionKey2 {
            get {
                return ((string)(this["SubscriptionKey2"]));
            }
            set {
                this["SubscriptionKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://southcentralus.api.cognitive.microsoft.com")]
        public string UriBase {
            get {
                return ((string)(this["UriBase"]));
            }
            set {
                this["UriBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://computervisiondemonstrator.cognitiveservices.azure.com/")]
        public string EndPoint {
            get {
                return ((string)(this["EndPoint"]));
            }
            set {
                this["EndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d114415a76b9474393f84862a456bcb1")]
        public string EndPointKey1 {
            get {
                return ((string)(this["EndPointKey1"]));
            }
            set {
                this["EndPointKey1"] = value;
            }
        }
    }
}
